//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDBDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACILITY
    {
        public string FACILITY_KEY { get; set; }
        public string CORP_KEY { get; set; }
        public string DEF_FACILITY_KEY { get; set; }
        public string FACILITY_TYPE { get; set; }
        public string FACILITY_ADDRESS { get; set; }
        public string FACILITY_ADDRESS2 { get; set; }
        public string FACILITY_CITY { get; set; }
        public string FACILITY_STATE { get; set; }
        public string FACILITY_ZIP { get; set; }
        public string FACILITY_FAX { get; set; }
        public string FACILITY_PHONE { get; set; }
        public string FACILITY_FEDERAL_ID { get; set; }
        public string NATIONAL_PROVIDER { get; set; }
        public string STATE_OPERATOR_NO { get; set; }
        public string STATE_PROVIDER { get; set; }
        public int FACILITY_ID { get; set; }
        public string FACILITY_REGION { get; set; }
        public string FAC_TYPE { get; set; }
        public string PROVIDER_TYPE { get; set; }
    }
}
