//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDBDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        public int MedicineID { get; set; }
        public string NDC { get; set; }
        public long PriceType { get; set; }
        public double Price { get; set; }
        public System.DateTime Date { get; set; }
    }
}
