//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDBDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NDC_M_PRICE
    {
        public string NDC { get; set; }
        public string NPT_TYPE { get; set; }
        public System.DateTime NPT_DATEC { get; set; }
        public Nullable<decimal> NPT_PRICEX { get; set; }
    }
}
