//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDBDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NDC_Discounts
    {
        public int NDC_DiscountID { get; set; }
        public string NDC { get; set; }
        public double Discount_Percent { get; set; }
        public Nullable<int> FacilityID { get; set; }
        public Nullable<int> DiscountID { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
    }
}
